=== Bernardo-MG/java-patterns-files/src/test/resources/files/xml/filtered/filtered_validation.dtd
<!ELEMENT test (value*)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value attribute1 (true|false) "false">
<!ATTLIST value attribute2 (true|false) "false">

=== Bernardo-MG/java-patterns-files/src/test/resources/files/xml/filtered/filtered_validation_a_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE test SYSTEM "filtered_validation.dtd">
<test>
	<value />
	<value attribute1="true">1</value>
	<value attribute2="true">1</value>
	<value attribute1="false" />
	<value attribute2="false" />
	<value attribute1="true" attribute2="false" />
	<value attribute1="false" attribute2="true" />
	<value attribute1="false" attribute2="false" />
	<value attribute1="true" attribute2="true" />
</test>
